# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
env:
  DOTNET_PROJECT: dock-dotnet-app
  REGISTRY: docker.io
  IMAGE_NAME: mouradl/dotnet-app:0.1

jobs:
  deploy:

    environment: ImageRegistry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install .NET
      - uses: actions/setup-dotnet@v2
      - name: Install dotnet-build-image
  	    run: dotnet tool install -g dotnet-build-image
      - name: Log in to Image registry
  	    run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $REGISTRY -u "${{ secrets.REGISTRY_USER }}" --password-stdin
      - name: Build and push image
  	    run: dotnet build-image --push "$DOTNET_PROJECT" -t "$REGISTRY/$IMAGE_NAME"  
